import type { Metadata } from "next";
import "./globals.css";
import { TopBar } from "@components/top-bar";
import { Toaster } from "@konekt/ui/sonner";
import { PeerConnectionProvider } from "@contexts/peer-connection";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="dark">
        <PeerConnectionProvider>
          <main className="flex flex-col h-screen">
            <TopBar />
            <div className="flex-grow overflow-auto">{children}</div>
            <Toaster position="top-right" closeButton />
          </main>
        </PeerConnectionProvider>
      </body>
    </html>
  );
}
