import type { Metadata } from "next";
import "./globals.css";
import { TopBar } from "@components/top-bar";
import { Toaster } from "@konekt/ui/sonner";
import { BaseProvider } from "contexts/base";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="dark">
        <main className="h-screen flex flex-col">
          <BaseProvider>
            <TopBar />
            <div className="flex-grow overflow-y-auto">{children}</div>
            <Toaster position="top-right" closeButton />
          </BaseProvider>
        </main>
      </body>
    </html>
  );
}
